# Generated by Django 4.2.24 on 2025-09-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_comment_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(blank=True, choices=[('autumn', '🍂 Autumn Special'), ('winter', '❄️ Winter Warmth'), ('spring', '🌸 Spring Fresh'), ('summer', '☀️ Summer Delight'), ('holiday', '🎄 Holiday Favorite'), ('quick', '⚡ Quick & Easy'), ('healthy', '🥗 Healthy Choice'), ('decadent', '💎 Indulgent Treat'), ('classic', '👑 Classic Recipe'), ('new', '✨ New Recipe'), ('popular', '🔥 Popular Choice'), ('', 'No Tag')], default='', help_text='Choose a tag to display as a badge on the recipe', max_length=20),
        ),
    ]
